FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py
ENV GROQ_API_KEY=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
ENV HUGGINGFACE_API_KEY=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

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]